### ISSUE TITLE
Ability to customize names

### ISSUE THREAD

**Issue by YilianSource** [harshhhdev/terminal-birthday#1]
## Description

At the moment the name of the person is hardcoded, would it be possible to make this accept some name as command line argument?

## Suggested implementation

We don't even need a fancy flag or something, just passing the exact name via an argument should be fine. Then we can congratulate that user specifically! 🎉 

If we're getting _really_ fancy, we could even fetch the default username from the OS, and use it as the default fallback:

```js
const os = require('os');

let name = process.argv[2] || os.userInfo().username;
```

**Comment by harshhhdev** [comment]
Nice suggestion. I was wanting to get back to this repository one day, this might be a reason to.

If you want to work on it, feel free to. Though otherwise I'll go ahead and implent it :)

**Comment by harshhhdev** [comment]
#2
